// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoutOut.API.Data;

#nullable disable

namespace ShoutOut.API.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20220810194219_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShoutOut.API.ShoutOut", b =>
                {
                    b.Property<int?>("SOId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("SOId"), 1L, 1);

                    b.Property<string>("SOComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SODateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SOEditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SOEdited")
                        .HasColumnType("bit");

                    b.Property<string>("SOTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SOId");

                    b.HasIndex("UserId");

                    b.ToTable("Shouts");
                });

            modelBuilder.Entity("ShoutOut.API.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShoutOut.API.ShoutOut", b =>
                {
                    b.HasOne("ShoutOut.API.User", "User")
                        .WithMany("ShoutOuts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoutOut.API.User", b =>
                {
                    b.Navigation("ShoutOuts");
                });
#pragma warning restore 612, 618
        }
    }
}
