
# 3. Create a GitHub Personal access token with "repo" and "read:packages" permissions. 
#
# 4. Create three app setti
name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: RevatureShoutOut
  DOCKER_REGISTRY_URL: docker.io
  IMAGE_USER: hawkinsr
  IMAGE_NAME: shoutout.api
  IMAGE_TAG: latest
  

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ SOCKER_REGUSTRY_URL }}/${{ env.IMAGE_USEER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
