# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - RevatureShoutOut

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_a6e99bd85ab649329cb7e5ced2da249e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1a5b4c7fe8924a8cb0b9a472727c75c0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a6e99bd85ab649329cb7e5ced2da249e }}/docker.io/hawkinsr/shoutout.api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'RevatureShoutOut'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6c1fa1c76c9b4ba4875580a81197d2de }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a6e99bd85ab649329cb7e5ced2da249e }}/docker.io/hawkinsr/shoutout.api:${{ github.sha }}'